### ISSUE TITLE
AssertionError： assert self._status is not None

### ISSUE THREAD

**Issue by highfleet** [zhongxinghong/PKUAutoElective#16]
### Version / Environment

System infomation: [ OS/X 10.15] \
Python version: [ 3.7.3] \
AutoElective version: [ 3.0.2] \

### Config

除courses外未更改其他配置

#### What

Assertion Fail: assert self._status is not None

#### Console Log

Exception in thread Elective:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/PKUAutoElective/autoelective/loop.py", line 527, in run_elective_loop
    raise e
  File "/PKUAutoElective/autoelective/loop.py", line 352, in run_elective_loop
    elif c in plans and c.is_available():
  File "/PKUAutoElective/autoelective/course.py", line 39, in is_available
    assert self._status is not None
AssertionError

#### Reproduce

每次运行时，似乎是账号登陆成功后的第一次loop就会出现。可能是什么原因呢？谢谢qwq（基本确定环境已经满足要求）

**Comment by yuanyehome** [comment]
同样的问题qwq
感觉可能是接口变了？程序貌似没有拿到该拿到的限制/已选人数

**Comment by zzy99** [comment]
目测是共同的问题，课满了就会这样

**Comment by highfleet** [comment]
> 同样的问题qwq
> 感觉可能是接口变了？程序貌似没有拿到该拿到的限制/已选人数

感觉有道理！ 手动刷课去了 作者大大加油~

**Comment by zhongxinghong** [comment]
不是 ... 这个是我写的 bug 试一下新的 v3.0.3 我已经修了 :(

**Comment by TsukimiRini** [comment]
> 不是 ... 这个是我写的 bug 试一下新的 v3.0.3 我已经修了 :(

哈哈哈，已经能正常使用了，大大辛苦

**Comment by highfleet** [comment]
> 不是 ... 这个是我写的 bug 试一下新的 v3.0.3 我已经修了 :(

辛苦啦
